/**
 * PM2 local-agent - generated by install-agent.ps1
 */
module.exports = {
  apps: [
    {
      name: 'venue-pos-agent',
      script: 'src/index.js',
      cwd: 'C:/Users/youss/OneDrive/Desktop/Venue_POS/apps/local-agent',
      interpreter: 'C:/Program Files/nodejs/node.exe',
      autorestart: true,
      max_restarts: 10,
      min_uptime: '5s',
      env: {
        NODE_ENV: 'production',
        PM2_HOME: 'C:/Users/youss/OneDrive/Desktop/Venue_POS/data/pm2',
        VENUE_POS_AGENT_ROOT: 'C:/Users/youss/OneDrive/Desktop/Venue_POS/apps/local-agent',
        VENUE_POS_INSTALL_ROOT: 'C:/Users/youss/OneDrive/Desktop/Venue_POS',
      },
    },
  ],
};
